### ISSUE TITLE
Nothing happens when I select 'Server Browser'

### ISSUE THREAD

**Issue by Daugeee** [Guad/GTACoop#27]
After I click on Server Browser, nothing happens at all, can't even reopen the menu by pressing F9.

It's not the scripthook either since I can open the Map Editor and Simple Native Trainer.

**Comment by techxpert211** [comment]
did you make the scripts folder? If so, remove those files and re insert them with everything in the client zip

**Comment by Daugeee** [comment]
You mean remove all the scripts and add the client folder files again?

**Comment by Guad** [comment]
Post your scripthookvdotnet-[date].log

**Comment by AhmedTaimour1** [comment]
same for me here is my scripthookvdotnet-[date].log pastebin http://pastebin.com/YTi9j81d 
mediafire : https://www.mediafire.com/?n7xc0yks7j81nh7

**Comment by Guad** [comment]
Update your .NET Framework

**Comment by AhmedTaimour1** [comment]
me?

**Comment by Guad** [comment]
Yes

**Comment by AhmedTaimour1** [comment]
wow it worked! thanks but online 1 server there xd :D (Y)

**Comment by Maxgold360** [comment]
[10:15:57] [DEBUG] Created script domain 'ScriptDomain_F7275A36'.
[10:15:57] [DEBUG] Loading scripts from 'D:\DoyoGames\Games\10103761\10103761\scripts' into script domain 'ScriptDomain_F7275A36' ...
[10:15:58] [DEBUG] Found 2 script(s) in 'GTACoOp.dll'.
[10:15:58] [DEBUG] Found 0 script(s) in 'Lidgren.Network.dll'.
[10:15:58] [DEBUG] Found 0 script(s) in 'NativeUI.dll'.
[10:15:58] [DEBUG] Found 0 script(s) in 'Newtonsoft.Json.dll'.
[10:15:59] [DEBUG] Found 0 script(s) in 'protobuf-net.dll'.
[10:15:59] [DEBUG] Starting 2 script(s) ...
[10:15:59] [DEBUG] Instantiating script 'GTACoOp.Main' in script domain 'ScriptDomain_F7275A36' ...
[10:16:03] [DEBUG] Started script 'GTACoOp.Main'.
[10:16:03] [DEBUG] Instantiating script 'GTACoOp.PedThread' in script domain 'ScriptDomain_F7275A36' ...
[10:16:03] [DEBUG] Started script 'GTACoOp.PedThread'.
[10:17:10] [ERROR] Script 'GTACoOp.Main' is not responding! Aborting ...
[10:17:11] [DEBUG] Aborted script 'GTACoOp.Main'.
[10:17:13] [ERROR] Caught fatal unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.ScriptDomain.ExecuteTask(IScriptTask task)
   at GTA.Native.Function.Call[T](UInt64 hash, InputArgument[] arguments)
   at GTA.UI.Notify(String message, Boolean blinking)
   at GTACoOp.Main.RebuildServerBrowser()
   at NativeUI.UIMenu.SelectItem()
   at NativeUI.MenuPool.ProcessControl()
   at GTACoOp.Main.OnTick(Object sender, EventArgs e)
   at GTA.Script.MainLoop()
[10:22:04] [DEBUG] Created script domain 'ScriptDomain_A026BA8D'.
[10:22:04] [DEBUG] Loading scripts from 'D:\DoyoGames\Games\10103761\10103761\scripts' into script domain 'ScriptDomain_A026BA8D' ...
[10:22:04] [DEBUG] Found 2 script(s) in 'GTACoOp.dll'.
[10:22:05] [DEBUG] Found 0 script(s) in 'Lidgren.Network.dll'.
[10:22:05] [DEBUG] Found 0 script(s) in 'NativeUI.dll'.
[10:22:05] [DEBUG] Found 0 script(s) in 'Newtonsoft.Json.dll'.
[10:22:06] [DEBUG] Found 0 script(s) in 'protobuf-net.dll'.
[10:22:06] [DEBUG] Starting 2 script(s) ...
[10:22:06] [DEBUG] Instantiating script 'GTACoOp.Main' in script domain 'ScriptDomain_A026BA8D' ...
[10:22:10] [DEBUG] Started script 'GTACoOp.Main'.
[10:22:10] [DEBUG] Instantiating script 'GTACoOp.PedThread' in script domain 'ScriptDomain_A026BA8D' ...
[10:22:10] [DEBUG] Started script 'GTACoOp.PedThread'.
[10:23:24] [ERROR] Script 'GTACoOp.Main' is not responding! Aborting ...
[10:23:24] [DEBUG] Aborted script 'GTACoOp.Main'.
[10:23:24] [ERROR] Caught fatal unhandled exception:
System.Threading.ThreadAbortException: Thread was being aborted.
   at Newtonsoft.Json.JsonReader.ReadAsStringInternal()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at GTACoOp.Main.RebuildServerBrowser()
   at NativeUI.UIMenu.SelectItem()
   at NativeUI.MenuPool.ProcessControl()
   at GTACoOp.Main.OnTick(Object sender, EventArgs e)
   at GTA.Script.MainLoop()
[10:26:04] [DEBUG] Unloading script domain 'ScriptDomain_A026BA8D' ...
[10:26:04] [DEBUG] Stopping 2 script(s) ...
[10:26:04] [DEBUG] Aborted script 'GTACoOp.PedThread'.
[10:26:05] [DEBUG] Deleted script domain 'ScriptDomain_A026BA8D'.
[10:26:07] [DEBUG] Created script domain 'ScriptDomain_7CC2789D'.
[10:26:07] [DEBUG] Loading scripts from 'D:\DoyoGames\Games\10103761\10103761\scripts' into script domain 'ScriptDomain_7CC2789D' ...
[10:26:07] [DEBUG] Found 2 script(s) in 'GTACoOp.dll'.
[10:26:07] [DEBUG] Found 0 script(s) in 'Lidgren.Network.dll'.
[10:26:07] [DEBUG] Found 0 script(s) in 'NativeUI.dll'.
[10:26:07] [DEBUG] Found 0 script(s) in 'Newtonsoft.Json.dll'.
[10:26:08] [DEBUG] Found 0 script(s) in 'protobuf-net.dll'.
[10:26:08] [DEBUG] Starting 2 script(s) ...
[10:26:08] [DEBUG] Instantiating script 'GTACoOp.Main' in script domain 'ScriptDomain_7CC2789D' ...
[10:26:11] [DEBUG] Started script 'GTACoOp.Main'.
[10:26:11] [DEBUG] Instantiating script 'GTACoOp.PedThread' in script domain 'ScriptDomain_7CC2789D' ...
[10:26:11] [DEBUG] Started script 'GTACoOp.PedThread'.

**Comment by Maxgold360** [comment]
HeLP THIS!

**Comment by JohnsonWhite** [comment]
Same Problem?    I changed the "client" files and my .NET Framework is on the newest Version. What do I do?

**Comment by JohnsonWhite** [comment]
// GTA V SCRIPT HOOK (build Dec 15 2016, v1.0.944.2)
//     (C) Alexander Blade 2015-2016
[15:49:08] INIT: Started
[15:49:08] INIT: Success, game version is VER_1_0_944_2_NOSTEAM
[15:49:08] INIT: Registering script 'ScriptHookVDotNet.asi' (0x00007FFF7E0C14A0)
[15:49:08] INIT: Registering script 'TrainerV.asi' (0x00007FFF6FF7F0C0)
[15:49:15] INIT: Pool 1 extended
[15:49:15] INIT: Pool 3 extended
[15:49:15] INIT: Pool 4 extended
[15:49:20] INIT: GtaThread collection size 188
[15:49:20] INIT: wnd proc 0x00000000FFFF083F
[15:49:20] INIT: IDXGISwapChain 0x00007FFFA60DD058 (0x00007FFF62D4C250)
[15:49:20] INIT: IDXGISwapChain set
[15:49:20] INIT: DX init started
[15:49:20] INIT: DX feature level A000
[15:49:20] INIT: DX init succeeded
[15:50:12] CORE: Requesting thread creation
[15:50:12] CORE: Creating threads
[15:50:14] CORE: Started control thread, id 32 active 1
[15:50:14] CORE: Started thread 'ScriptHookVDotNet.asi' (0x00007FFF7E0C14A0), id 33 active 1
[15:50:14] CORE: Started thread 'TrainerV.asi' (0x00007FFF6FF7F0C0), id 34 active 1
[15:50:14] CORE: Launching main() for 'ScriptHookVDotNet.asi' (0x00007FFF7E0C14A0), id 33
[15:50:14] CORE: Launching main() for 'TrainerV.asi' (0x00007FFF6FF7F0C0), id 34
[16:02:59] UNINIT: Unregistering script 'TrainerV.asi'
[16:02:59] UNINIT: Unregistering script 'ScriptHookVDotNet.asi'

**Comment by SauerkrautSchnitzel** [comment]
same problem with the server browser but a different log. i use the newest version (1.41) of gta and the needed files. 

> [12:07:30] [DEBUG] Created script domain 'ScriptDomain_DBAC724C' with v2.10.2.
[12:07:30] [DEBUG] Loading scripts from 'D:\Spiele\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_DBAC724C' ...
[12:07:30] [INFO] Loading assembly 'GTACoOp.dll' ...
[12:07:30] [DEBUG] Found 2 script(s) in 'GTACoOp.dll'.
[12:07:30] [INFO] Loading assembly 'Lidgren.Network.dll' ...
[12:07:30] [DEBUG] Found 0 script(s) in 'Lidgren.Network.dll'.
[12:07:30] [INFO] Loading assembly 'MaxMind.Db.dll' ...
[12:07:30] [DEBUG] Found 0 script(s) in 'MaxMind.Db.dll'.
[12:07:30] [INFO] Loading assembly 'MaxMind.GeoIP2.dll' ...
[12:07:30] [DEBUG] Found 0 script(s) in 'MaxMind.GeoIP2.dll'.
[12:07:30] [INFO] Loading assembly 'NativeUI.dll' ...
[12:07:30] [DEBUG] Found 1 script(s) in 'NativeUI.dll'.
[12:07:30] [INFO] Loading assembly 'Newtonsoft.Json.dll' ...
[12:07:30] [DEBUG] Found 0 script(s) in 'Newtonsoft.Json.dll'.
[12:07:30] [INFO] Loading assembly 'protobuf-net.dll' ...
[12:07:30] [DEBUG] Found 0 script(s) in 'protobuf-net.dll'.
[12:07:30] [DEBUG] Starting 3 script(s) ...
[12:07:30] [DEBUG] Instantiating script 'GTACoOp.Main' in script domain 'ScriptDomain_DBAC724C' ...
[12:07:31] [DEBUG] Started script 'GTACoOp.Main'.
[12:07:31] [DEBUG] Instantiating script 'GTACoOp.PedThread' in script domain 'ScriptDomain_DBAC724C' ...
[12:07:31] [DEBUG] Started script 'GTACoOp.PedThread'.
[12:07:31] [DEBUG] Instantiating script 'NativeUI.BigMessageThread' in script domain 'ScriptDomain_DBAC724C' ...
[12:07:31] [DEBUG] Started script 'NativeUI.BigMessageThread'.
[19:31:46] [ERROR] Script 'GTACoOp.Main' is not responding! Aborting ...
[19:31:46] [DEBUG] Aborted script 'GTACoOp.Main'.
[19:31:46] [ERROR] Caught fatal unhandled exception:
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei GTA.ScriptDomain.ExecuteTask(IScriptTask task)
   bei GTA.Native.Function.Call[T](UInt64 hash, InputArgument[] arguments)
   bei GTA.UI.Notify(String message, Boolean blinking)
   bei GTACoOp.Main.OnTick(Object sender, EventArgs e)
   bei GTA.Script.raise_Tick(Object value0, EventArgs value1)
   bei GTA.Script.MainLoop()
