### ISSUE TITLE
Nothing happens when I select 'Server Browser'

### ISSUE THREAD

**Issue by RAWSKELLZ** [Guad/GTACoop#39]
After I click on Server Browser, nothing happens at all, can't even reopen the menu by pressing F9.

Version of the game from Rockstar Warehouse 1.0.617.1
[ScriptHookV](http://www.dev-c.com/gtav/scripthookv): 1.0.335.2-1.0.617.1
[ScriptHookVDotNet](https://github.com/crosire/scripthookvdotnet/releases): 2.5.1
CO-OP: 0.9

**Comment by Guad** [comment]
Post your scripthookvdotnet-[date].log

**Comment by RAWSKELLZ** [comment]
[ScriptHookVDotNet-2016-02-06.log](https://github.com/Guad/GTACoop/files/120321/ScriptHookVDotNet-2016-02-06.log.txt) or [PasteBin](http://pastebin.com/JXrSgG9a)

**Comment by AhmedTaimour1** [comment]
same here any help please? fast?

**Comment by Maxgold360** [comment]
Help Me too Guad!

My ScriptHookVDotNet[date].log:

[10:15:57] [DEBUG] Created script domain 'ScriptDomain_F7275A36'.
[10:15:57] [DEBUG] Loading scripts from 'D:\DoyoGames\Games\10103761\10103761\scripts' into script domain 'ScriptDomain_F7275A36' ...
[10:15:58] [DEBUG] Found 2 script(s) in 'GTACoOp.dll'.
[10:15:58] [DEBUG] Found 0 script(s) in 'Lidgren.Network.dll'.
[10:15:58] [DEBUG] Found 0 script(s) in 'NativeUI.dll'.
[10:15:58] [DEBUG] Found 0 script(s) in 'Newtonsoft.Json.dll'.
[10:15:59] [DEBUG] Found 0 script(s) in 'protobuf-net.dll'.
[10:15:59] [DEBUG] Starting 2 script(s) ...
[10:15:59] [DEBUG] Instantiating script 'GTACoOp.Main' in script domain 'ScriptDomain_F7275A36' ...
[10:16:03] [DEBUG] Started script 'GTACoOp.Main'.
[10:16:03] [DEBUG] Instantiating script 'GTACoOp.PedThread' in script domain 'ScriptDomain_F7275A36' ...
[10:16:03] [DEBUG] Started script 'GTACoOp.PedThread'.
[10:17:10] [ERROR] Script 'GTACoOp.Main' is not responding! Aborting ...
[10:17:11] [DEBUG] Aborted script 'GTACoOp.Main'.
[10:17:13] [ERROR] Caught fatal unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.ScriptDomain.ExecuteTask(IScriptTask task)
   at GTA.Native.Function.Call[T](UInt64 hash, InputArgument[] arguments)
   at GTA.UI.Notify(String message, Boolean blinking)
   at GTACoOp.Main.RebuildServerBrowser()
   at NativeUI.UIMenu.SelectItem()
   at NativeUI.MenuPool.ProcessControl()
   at GTACoOp.Main.OnTick(Object sender, EventArgs e)
   at GTA.Script.MainLoop()
[10:22:04] [DEBUG] Created script domain 'ScriptDomain_A026BA8D'.
[10:22:04] [DEBUG] Loading scripts from 'D:\DoyoGames\Games\10103761\10103761\scripts' into script domain 'ScriptDomain_A026BA8D' ...
[10:22:04] [DEBUG] Found 2 script(s) in 'GTACoOp.dll'.
[10:22:05] [DEBUG] Found 0 script(s) in 'Lidgren.Network.dll'.
[10:22:05] [DEBUG] Found 0 script(s) in 'NativeUI.dll'.
[10:22:05] [DEBUG] Found 0 script(s) in 'Newtonsoft.Json.dll'.
[10:22:06] [DEBUG] Found 0 script(s) in 'protobuf-net.dll'.
[10:22:06] [DEBUG] Starting 2 script(s) ...
[10:22:06] [DEBUG] Instantiating script 'GTACoOp.Main' in script domain 'ScriptDomain_A026BA8D' ...
[10:22:10] [DEBUG] Started script 'GTACoOp.Main'.
[10:22:10] [DEBUG] Instantiating script 'GTACoOp.PedThread' in script domain 'ScriptDomain_A026BA8D' ...
[10:22:10] [DEBUG] Started script 'GTACoOp.PedThread'.
[10:23:24] [ERROR] Script 'GTACoOp.Main' is not responding! Aborting ...
[10:23:24] [DEBUG] Aborted script 'GTACoOp.Main'.
[10:23:24] [ERROR] Caught fatal unhandled exception:
System.Threading.ThreadAbortException: Thread was being aborted.
   at Newtonsoft.Json.JsonReader.ReadAsStringInternal()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at GTACoOp.Main.RebuildServerBrowser()
   at NativeUI.UIMenu.SelectItem()
   at NativeUI.MenuPool.ProcessControl()
   at GTACoOp.Main.OnTick(Object sender, EventArgs e)
   at GTA.Script.MainLoop()
[10:26:04] [DEBUG] Unloading script domain 'ScriptDomain_A026BA8D' ...
[10:26:04] [DEBUG] Stopping 2 script(s) ...
[10:26:04] [DEBUG] Aborted script 'GTACoOp.PedThread'.
[10:26:05] [DEBUG] Deleted script domain 'ScriptDomain_A026BA8D'.
[10:26:07] [DEBUG] Created script domain 'ScriptDomain_7CC2789D'.
[10:26:07] [DEBUG] Loading scripts from 'D:\DoyoGames\Games\10103761\10103761\scripts' into script domain 'ScriptDomain_7CC2789D' ...
[10:26:07] [DEBUG] Found 2 script(s) in 'GTACoOp.dll'.
[10:26:07] [DEBUG] Found 0 script(s) in 'Lidgren.Network.dll'.
[10:26:07] [DEBUG] Found 0 script(s) in 'NativeUI.dll'.
[10:26:07] [DEBUG] Found 0 script(s) in 'Newtonsoft.Json.dll'.
[10:26:08] [DEBUG] Found 0 script(s) in 'protobuf-net.dll'.
[10:26:08] [DEBUG] Starting 2 script(s) ...
[10:26:08] [DEBUG] Instantiating script 'GTACoOp.Main' in script domain 'ScriptDomain_7CC2789D' ...
[10:26:11] [DEBUG] Started script 'GTACoOp.Main'.
[10:26:11] [DEBUG] Instantiating script 'GTACoOp.PedThread' in script domain 'ScriptDomain_7CC2789D' ...
[10:26:11] [DEBUG] Started script 'GTACoOp.PedThread'.
