### ISSUE TITLE
Error loading AdminTools

### ISSUE THREAD

**Issue by SuperArmySoldiers** [Guad/GTACoop#86]
Getting this error. Any ideas?

`Microsoft Windows [Version 6.3.9600](c) 2013 Microsoft Corporation. All rights reserved.

\GTAV Server Password>chcp 65001
Active code page: 65001

\GTAV Server Password>
Name: EU Gaming Group | LSPDFR ONLY PW @ site | www.eugaminggroup.com
IPs: 81.19.208.67/192.168.70.1/192.168.50.1/127.0.0.1:5001
Player Limit: 50
Starting...
Announcing to master server...
Loading filterscripts..
Failed to load filterscript "AdminTools", error: Could not load file or assembly
 'file:///C:***\GTAV Server Password\filte
rscripts\AdminTools.dll' or one of its dependencies. Operation is not supported.
 (Exception from HRESULT: 0x80131515)
Servers returned by master server: 90
Started! Waiting for connections.
`

**Comment by Bluscream** [comment]
right-click on the dll -> properties -> unlbock.
also try starting GTAServer.exe as admin

**Comment by SuperArmySoldiers** [comment]
Thanks seems to be working!

Server back up

**Comment by SuperArmySoldiers** [comment]
Not working

`Microsoft Windows [Version 6.3.9600](c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Administrator\Desktop\Game Servers\GTAV Server Password>chcp 65001
Active code page: 65001

C:\Users\Administrator\Desktop\Game Servers\GTAV Server Password>
Name: EU Gaming Group | LSPDFR ONLY PW @ site | www.eugaminggroup.com
IPs: 81.19.208.67/192.168.70.1/192.168.50.1/127.0.0.1:5001
Player Limit: 50
Starting...
Announcing to master server...
Loading filterscripts..
[30/07/2016 11:53:05](SUCCESS) ADMINTOOLS: Accounts loaded.
[30/07/2016 11:53:05](SUCCESS) ADMINTOOLS: Bans loaded.
Starting filterscript Server Administration Tools...
Servers returned by master server: 144
Started! Waiting for connections.

Unhandled Exception: System.NullReferenceException: Object reference not set to
an instance of an object.
   at GTAServer.GameServer.Tick()
   at GTAServer.Program.Main(String[] args)
`

**Comment by Bluscream** [comment]
Do you even have the newest Version?

**Comment by SuperArmySoldiers** [comment]
Yeah... You posted on my site with the link.
Was working fine then I used the update and now it doesn't

**Comment by Bluscream** [comment]
You cannot have the newest version, it would tell you "Can't handle this tick" if there would be an error where you have it. delete your whole gta server folder, redownload and re-setup everything.

**Comment by SuperArmySoldiers** [comment]
All I have done is downloaded the latest version and put in the user database and server details into it.

I'll redownload it tomorrow

**Comment by SuperArmySoldiers** [comment]
Yeah no nothing is working now. 

Using the default files I unblocked all the .dll files and it crashed straight away.

Going to use the old version. 
- Edit. Old files dont even work now. No idea whats wrong with it. They all just shut down

**Comment by Bluscream** [comment]
Probably post some screenshots/console logs etc. I can't help ya with just 'it shuts down'

**Comment by SuperArmySoldiers** [comment]
Where can I get logs from? Cant see any log files

**Comment by Bluscream** [comment]
the server only logs to console.

**Comment by SuperArmySoldiers** [comment]
agh then we have a problem. 
If the program crashes - no console. = no logs. :(

**Comment by SuperArmySoldiers** [comment]
Managed to get a chance to copy the console - This is the update. 
Old version now working again. 

`Microsoft Windows [Version 6.3.9600](c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Administrator\Desktop\GTAV Server>chcp 65001
Active code page: 65001

C:\Users\Administrator\Desktop\GTAV Server>
Name: Simple GTA Server
IPs: 81.19.208.67/192.168.70.1/192.168.50.1/127.0.0.1:4500
Player Limit: 16
Starting...

Unhandled Exception: System.Net.Sockets.SocketException: Only one usage of each
socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress
socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Lidgren.Network.NetPeer.BindSocket(Boolean reBind)
   at Lidgren.Network.NetPeer.InitializeNetwork()
   at Lidgren.Network.NetPeer.Start()
   at GTAServer.GameServer.Start(String[] filterscripts)
   at GTAServer.Program.Main(String[] args)
`

**Comment by SuperArmySoldiers** [comment]
`Microsoft Windows [Version 6.3.9600](c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Administrator\Desktop\LSPDFR>chcp 65001
Active code page: 65001

C:\Users\Administrator\Desktop\LSPDFR>
Name: EU Gaming Group | LSPDFR TEST
IPs: 81.19.208.67/192.168.70.1/192.168.50.1/127.0.0.1:4497
Player Limit: 16
Starting...
Announcing to master server...
Loading filterscripts..
[31/07/2016 17:25:21](SUCCESS) ADMINTOOLS: Accounts loaded.
[31/07/2016 17:25:22](SUCCESS) ADMINTOOLS: Bans loaded.
Starting filterscript Server Administration Tools...
Servers returned by master server: 138
Started! Waiting for connections.

Unhandled Exception: System.NullReferenceException: Object reference not set to
an instance of an object.
   at GTAServer.GameServer.Tick()
   at GTAServer.Program.Main(String[] args)
`

**Comment by Bluscream** [comment]
https://github.com/Guad/GTACoop/issues/86#issuecomment-236421769 That one is pretty easy to explain, it means that you are have 2 servers running on the same port.

**Comment by Bluscream** [comment]
https://github.com/Guad/GTACoop/issues/86#issuecomment-236439355 i don't think that one can happen in the newest version though.

**Comment by Bluscream** [comment]
btw, these are all outdated versions. the newest servers shows this when starting:

```
[2016-08-01 04:36:43] (DEBUG) FILE: Settings loaded from D:\SERVERS\GameServer\Grand Theft Auto\GTA V\Settings.xml
IPs: 127.0.0.1:4499
Name: [~d~EU~s~/~l~G~r~E~y~R~s~] Blu's World (LSPD:FR/Roleplay/Fun~w~)
Player Limit: 16
Starting...
Announcing to master server...
Failed to announce self: master server is not available at this time.
Loading filterscripts..
[2016-08-01 04:36:47] (SUCCESS) ADMINTOOLS: Accounts loaded.
[2016-08-01 04:36:47] (SUCCESS) ADMINTOOLS: Bans loaded.
Starting filterscript Server Administration Tools...
Server Info: Name: [~d~EU~s~/~l~G~r~E~y~R~s~] Blu's World (LSPD:FR/Roleplay/Fun~w~) | Password?: False | Players: 0 / 16 | Gamemode: FreeRoam |
Servers returned by master server: 35
Started! Waiting for connections.
```

**Comment by Bluscream** [comment]
@SuperArmySoldiers Download this: https://github.com/Bluscream/GTACoop/releases/download/0.9.2-hotfix/Server.zip
**AND REMEMBER TO ALSO DELETE YOUR ACCOUNTS.XML, SETTINGS.XML AND BANLIST.XML**

**Comment by SuperArmySoldiers** [comment]
Ill try this hot fix tonight. Thanks

**Comment by SuperArmySoldiers** [comment]
Seems to be working now! 

I do get these requests though... this normal?

`[01/08/2016 18:29:03](DEBUG) FILE: Settings loaded from C:\Users\Administrator\
Desktop\Game Servers\GTAV Server PW\Settings.xml
IPs: 127.0.0.1:4499
Name: EU Gaming Group | pw @ site | www.eugaminggroup.com
Player Limit: 50
Starting...
Announcing to master server...
Loading filterscripts..
Server Info: Name: EU Gaming Group | pw @ site | www.eugaminggroup.com | Passwor
d?: True | Players: 0 / 50 | Gamemode: freeroam |
Servers returned by master server: 102
Started! Waiting for connections.
[01/08/2016 18:29:20](DEBUG) NETWORK: Server Status requested by 91.205.209.137

[01/08/2016 18:29:31](DEBUG) NETWORK: Server Status requested by 171.101.11.145

[01/08/2016 18:29:47](DEBUG) NETWORK: Server Status requested by 81.65.11.134
[01/08/2016 18:29:49](DEBUG) NETWORK: Server Status requested by 81.65.11.134
[01/08/2016 18:29:49](DEBUG) NETWORK: Server Status requested by 81.65.11.134
[01/08/2016 18:29:57](DEBUG) NETWORK: Server Status requested by 213.14.158.232

[01/08/2016 18:29:58](DEBUG) NETWORK: Server Status requested by 81.65.11.134
[01/08/2016 18:30:09](DEBUG) NETWORK: Server Status requested by 85.230.72.189
[01/08/2016 18:30:10](DEBUG) NETWORK: Server Status requested by 213.14.158.232

[01/08/2016 18:30:16](DEBUG) NETWORK: Server Status requested by 91.205.209.137

[01/08/2016 18:30:17](DEBUG) NETWORK: Server Status requested by 79.118.156.104

[01/08/2016 18:30:17](DEBUG) NETWORK: Server Status requested by 77.139.145.226

`

**Comment by Bluscream** [comment]
Yes, that means that someone opened the serverlist and your server showed up on his screen.

**Comment by manxxxxdark** [comment]
I am getting this error

Name: Simple GTA Server
Port: 4499
Player Limit: 16
Starting...
Announcing to master server...
Failed to announce self: master server is not available at this time.
Loading filterscripts..
Failed to load filterscript "AdminTools", error: Could not load file or assembly 'file:///E:\GTA V\Grand Theft Auto V\server\filterscripts\AdminTools.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Started! Waiting for connections.

**Comment by VAIBHAV564** [comment]
My says 
[20-03-2017 21:27:37] (DEBUG) FILE: Settings loaded from C:\Program Files (x86)\
Grand Theft Auto V\SERVER\Settings.xml
IPs: 127.0.0.1:4499
Name: Simple GTA Server
Player Limit: 16
Starting...
Announcing to master server...
Failed to announce self: master server is not available at this time.
Loading filterscripts..
Server Info: Name: Simple GTA Server | Password?: False | Players: 0 / 16 | Game
mode: freeroam |
Could not contact master server: The remote server returned an error: (404) Not
Found.
Started! Waiting for connections.
Failed to announce self: master server is not available at this time.
      what to do ?????

**Comment by thejas894** [comment]
[18-May-18 6:44:30 PM] (DEBUG) FILE: Settings loaded from E:\Grand Theft Auto V\server\Settings.xml
IPs: 127.0.0.1:4499
Name: Simple GTA Server
Player Limit: 16
Starting...
Announcing to master server...
Failed to announce self: master server is not available at this time.
Loading filterscripts..
Server Info: Name: Simple GTA Server | Password?: False | Players: 0 / 16 | Gamemode: freeroam |
Could not contact master server: Unable to connect to the remote server
Started! Waiting for connections.

**Comment by thejas894** [comment]
Pls give me a fix asap. Thanks.

**Comment by Bluscream** [comment]
Nope, this project is deprecated
